### ISSUE TITLE
tiered_ImageNet的代码及超参数能提供么？

### ISSUE THREAD

**Issue by xue19890510** [Fei-Long121/DeepBDC#10]
你好，代码中只提供了mini-imagenet 和 cu b的代码及超参数，您看能否提供tired-image的超参数脚本？
tired-image的代码和其他两个数据集一样么？  
这里的代码主要是数据集相关的代码

在请教下  cub 和tiered_ImageNet 在STLBDC中的预训练阶段batch size 都是64么？

**Comment by Fei-Long121** [comment]
您好，感谢关注! Tiered_ImageNet的相关代码后期会尽快开源，预训练时的batch_size均为64。

**Comment by xue19890510** [comment]
您好，tiered_ImageNet的STL BDC  代码及配置文件 能先公布么，等着调试用 ？

**Comment by guoqianyu-alberta** [comment]
您好！感谢您分享代码，是否可以分享一下tiered的model参数？如果有麻烦，是否可以发送到我的邮箱：qyguo20@fudan.edu.cn 谢谢您！

**Comment by stu-yue** [comment]
非常感谢作者的代码分享，另外想请您分享下tiered的代码及配置文件，可否发到我的邮箱：737254958@qq.com，不胜感激！
