### ISSUE TITLE
cub 复现结果1shot 5shot分别差3个点 一个点，有什么要注意的地方么？

### ISSUE THREAD

**Issue by xue19890510** [Fei-Long121/DeepBDC#11]
你好，用您的代码达不到论文中提到的结果，有什么要注意的么

**Comment by Fei-Long121** [comment]
您好，感谢关注！我们发布的代码在不同的设备和环境上都经过训练和测试，均能达到论文的结果(不同环境得到的结果略有差异)；同时，有多位同行在复现时经过邮件交流，据同行的反馈情况来看，在误差范围内，代码也是均能复现的。对于您所提到的情况，请考虑数据集的原因：我们使用的数据集在Datasets一栏已经进行了说明，请直接到对应链接下载使用即可。如果您使用自己准备的数据集，考虑到数据集的不同划分，不同的分辨率等问题，可能出现您现在所提出的现象。
