### ISSUE TITLE
关于初始化的预训练模型

### ISSUE THREAD

**Issue by ningding97** [Fei-Long121/DeepBDC#14]
感谢贡献这个非常棒的工作！ 请问在训练中用来initialization的预训练的模型是对应Google Drive和Baidu Drive提供的吗？还是说这些是已经用DeepBDC训练好的模型

**Comment by ningding97** [comment]
我理解预训练模型是run_pretrain.sh得到的，Google Drive中的是episodic等方法训练好之后的模型？

**Comment by Fei-Long121** [comment]
您好！感谢您的关注，我们发布的模型既包括运行run_pretrain.sh得到的模型(预训练)，也包括运行run_metatrain.sh后得到的模型(元训练)。
