### ISSUE TITLE
关于度量

### ISSUE THREAD

**Issue by ltc123ltc** [Fei-Long121/DeepBDC#16]
你好，我看了关于DBC的代码，其中meata_deepdbc.py中metric度量函数似乎是用的欧氏距离，论文中所用的符号tr(·)表示矩阵的迹，但我似乎并没有找到相应的代码，是我忽略了哪部分代码吗，还是在元学习框架中确实使用欧氏距离而不是迹

**Comment by Fei-Long121** [comment]
您好,  感谢关注！论文中的实验，我们在1-shot时利用了内积的方式(对应于矩阵的迹的形式)，在5-shot时使用了欧氏距离，论文中有相应的消融实验，您可以参考一下。
