### ISSUE TITLE
Question about dropblock in ResNet-12

### ISSUE THREAD

**Issue by leesb7426** [Fei-Long121/DeepBDC#17]
First, thank you for your wonderful paper and tailored code.

I found some differences between paper and code.
In your paper, DropBlock regularization is utilized for ResNet-12 during training.
However, in your code (ResNet-12 of models/backbones/ResNet.py), the drop_rate is always 0.
Then, the DropBlock doesn't apply.

In addition, when A was adjusted to 0.1, it shows low performance than when DropBlock was not used.
Please explain this phenomenon.

**Comment by leesb7426** [comment]
Hello

**Comment by Fei-Long121** [comment]
could you please provide your email address?

**Comment by leesb7426** [comment]
This is my email:leesb7426@gmail.com
