### ISSUE TITLE
about input_dim

### ISSUE THREAD

**Issue by colorfuloranges** [Fei-Long121/DeepBDC#18]
您好，非常感谢您的贡献。我想请教您一个问题，我想把BDC模块插入到我网络的二维卷积之后，二维卷积输出的特征维度是[8,64,11,11],我在使用的时候是不是input_dim=[64 11 11]这样进行设置呢？很期待您的回复，谢谢啦！

**Comment by Fei-Long121** [comment]
您好，感谢关注！在BDC类的初始化函数里，参数input_dim表示为卷积神经网络输出的3位张量的维度，组成形式为[通道数，特征图的高，特征图的宽]，您的设置是正确的。
