### ISSUE TITLE
与风格Gram matrix的关系

### ISSUE THREAD

**Issue by weifengchiu** [Fei-Long121/DeepBDC#2]
以下是一些个人见解和疑惑，作者可以回答一下么：
        我理解这工作核心，在于使用预训练模型的feature map(记为X)，然后计算BDC来抽取图片的特征。而BDC就是X的列的欧氏距离经过一些归一化操作得到的。在神经风格中，使用Gram矩阵来描述图片的风格(记为G)，G=(X^T) X。文章中公式(6)第一行也提到了A = G_ii + G_jj - 2*G_ij；公式第二行、第三行分别做了开根号，和移除行、列的均值的操作。
        那么可以想象，如果两张图片的Gram矩阵很接近，BDC模块提取的特征也会非常接近，也就是说他们会被认为是同一类。而我们知道Gram矩阵是跟纹理、风格相关的，而跟内容关系不大。那是否可以理解为，最终抽取的特征其实是图片纹理或风格？

**Comment by Fei-Long121** [comment]
您好，首先感谢您对我们工作的关注。对于您的见解和疑惑，我们是这样思考的：图像高层卷积特征之间的协方差矩阵（或Gram矩阵）是刻画图像各个特征之间的相关性，强化了局部之间的关联，能够更好的利用特征之间的二阶统计信息去建模图像的表征。在以这种表征进行分类的端到端学习框架里，经过训练，可以充分学习到图像卷积特征语义层面上的相关，以此表征进行分类，能获得显著的性能提升。而在风格迁移框架里，骨干模型使用的是固定的预训练好的权重，这种情况下得到的特征协方差矩阵可能仅是一些general的图像信息之间的相关，无法代表高层的语义相关。我们的DeepBDC是一种端到端的网络框架，以BDC矩阵建模图像的表征主导网络的训练，利用高层语义特征之间的相关可以捕获图像之间更细微的差异，同时BDC能够建模非线性相关，而协方差只能建模线性相关，因此相对来说建模能力更强。除此之外，BDC测度考虑了图像对之间的联合分布，能够更好的度量图像之间的相似度。
       希望我们的回复能对您有所帮助。

**Comment by weifengchiu** [comment]
> 
        你好，感谢回答！
        我之前不是没关注过这个领域，可能理解有些偏差，昨天晚上又去看了一些您文章的引用文献，发现在bilinear pooling、CovNet等都是这么做的，文献的作者也没有太多解释。
        是否可以理解为，这类方法能够work，很关键的是在backbone后面增加的全连接层(conv1x1)，但是几乎所有文章里面都将他的作用称之为降维。
        另外，还是没有解答的，如果两张图片的G一样，那bilinear pooling，或BDC应该都是一样的。
<img width="458" alt="image" src="https://user-images.githubusercontent.com/26971640/165009987-1aeea416-8bb1-400e-896d-30ce1be3e6f0.png">
所以原则上bilinear pooling，CovNet或BDC不应该包含比G更多的信息，这个悖论怎么理解？

**Comment by weifengchiu** [comment]
你好，感谢回答！
     我之前不是没关注过这个领域，可能理解有些偏差，昨天晚上又去看了一些您文章的引用文献，发现在bilinear pooling、CovNet等都是这么做的，文献的作者也没有太多解释。
     是否可以理解为，这类方法能够work，很关键的是在backbone后面增加的全连接层(conv1x1)，但是几乎所有文章里面都将他的作用称之为降维。
     另外，还是没有解答的，如果两张图片的G一样，那bilinear pooling，或BDC应该都是一样的。所以原则上bilinear pooling，CovNet或BDC不应该包含比G更多的信息，这个悖论怎么理解？
<img width="458" alt="image" src="https://user-images.githubusercontent.com/26971640/165009987-1aeea416-8bb1-400e-896d-30ce1be3e6f0.png">

**Comment by PeihuaLi** [comment]
感谢这个insightful而且interesting的问题！Fei-Long121的回答比较全面，我在此做些补充。

>那是否可以理解为，最终抽取的特征其实是图片纹理或风格？

是的，BDC矩阵可以理解为提取图像的纹理或风格.

接下来是更详细的解释

从计算(computing)的角度上来说, 
(1)Gram矩阵实际上是相关矩阵/二阶原点矩阵(https://en.wikipedia.org/wiki/Autocorrelation#Matrix)，建模各个通道/特征图之间的内积，即线性相关性；
(2) BDC矩阵建模各个通道/特征图之间的非线性相关性，这是通过计算各个通道/特征图之间的欧式距离(再进行正规化)实现的，见公式(6)。

实际上，在二阶池化的语境下，我们在论文3.2节最后一段讨论了BDC矩阵与协方差矩阵之间的关系 (注: 协方差矩阵与相关矩阵/二阶原点矩矩阵本质上是相同的)。

从理论(theory)的角度上来说，
(1）关于Gram矩阵(即二阶原点矩)，根据概率密度函数pdf与矩函数的关系(https://en.wikipedia.org/wiki/Moment-generating_function)，一个pdf可以写成所有n阶矩(n=0,1, 2, …)的线性组合, 因此Gram矩阵是概率密度函数的近似。在风格转换中，只约束单独内容图像的分布(Gram矩阵)与单独风格图像的分布相近，在优化过程中并不考虑二者的联合分布。
(2) 在BDC的理论中，通过考虑内容图像和风格图像的联合分布比较二者在统计意义上的依赖关系。对于离散采样(即图像特征)，BDC度量得以简化并解耦，二者的依赖关系可以通过内容图像BDC矩阵和风格图像BDC矩阵的距离或相似度来表示。

我很期待看到DeepBDC在风格转换中的应用。

**Comment by weifengchiu** [comment]
> 是的，BDC矩阵可以理解为提取图像的纹理或风格.
 
> 我很期待看到DeepBDC在风格转换中的应用。

        感谢回复，确实相较于Gram矩阵，理论上使用BDC矩阵应该能更好的实现风格的提取，使用deepBDC也许会得到更加真实的风格迁移图片，这是值得研究的一个方向。
        但是我在这里关心的点是，如果相比于直接对预训练的feature map直接做global average pooling等操作(good emb的做法)，去计算deepBDC矩阵，得到的特征更加偏向于纹理，那么这样做的鲁棒性如何，比如在Stylized ImageNet上的表现？

**Comment by Fei-Long121** [comment]
> > 是的，BDC矩阵可以理解为提取图像的纹理或风格.
> 
> > 我很期待看到DeepBDC在风格转换中的应用。
> 
> 感谢回复，确实相较于Gram矩阵，理论上使用BDC矩阵应该能更好的实现风格的提取，使用deepBDC也许会得到更加真实的风格迁移图片，这是值得研究的一个方向。 但是我在这里关心的点是，如果相比于直接对预训练的feature map直接做global average pooling等操作(good emb的做法)，去计算deepBDC矩阵，得到的特征更加偏向于纹理，那么这样做的鲁棒性如何，比如在Stylized ImageNet上的表现？

您好！很抱歉现在才回复您，目前我们暂时还没有系统地评估过相关实验。后面如果我们做了相关评估实验，会及时联系您。

**Comment by weifengchiu** [comment]
> > > 是的，BDC矩阵可以理解为提取图像的纹理或风格.
> > 
> > 
> > > 我很期待看到DeepBDC在风格转换中的应用。
> > 
> > 
> > 感谢回复，确实相较于Gram矩阵，理论上使用BDC矩阵应该能更好的实现风格的提取，使用deepBDC也许会得到更加真实的风格迁移图片，这是值得研究的一个方向。 但是我在这里关心的点是，如果相比于直接对预训练的feature map直接做global average pooling等操作(good emb的做法)，去计算deepBDC矩阵，得到的特征更加偏向于纹理，那么这样做的鲁棒性如何，比如在Stylized ImageNet上的表现？
> 
> 您好！很抱歉现在才回复您，目前我们暂时还没有系统地评估过相关实验。后面如果我们做了相关评估实验，会及时联系您。

好的，感谢

**Comment by weifengchiu** [comment]
> > > 是的，BDC矩阵可以理解为提取图像的纹理或风格.
> > 
> > 
> > > 我很期待看到DeepBDC在风格转换中的应用。
> > 
> > 
> > 感谢回复，确实相较于Gram矩阵，理论上使用BDC矩阵应该能更好的实现风格的提取，使用deepBDC也许会得到更加真实的风格迁移图片，这是值得研究的一个方向。 但是我在这里关心的点是，如果相比于直接对预训练的feature map直接做global average pooling等操作(good emb的做法)，去计算deepBDC矩阵，得到的特征更加偏向于纹理，那么这样做的鲁棒性如何，比如在Stylized ImageNet上的表现？
> 
> 您好！很抱歉现在才回复您，目前我们暂时还没有系统地评估过相关实验。后面如果我们做了相关评估实验，会及时联系您。

请问有新的进展了吗
