### ISSUE TITLE
About how to run the cross-domain experiment?

### ISSUE THREAD

**Issue by JiaHg** [Fei-Long121/DeepBDC#21]
Hi, i am so interseted in your DeepBDC! I wonder how to run the cross-domain experiment in your paper. Thanks in advanced.

**Comment by Fei-Long121** [comment]
Hi, JiaHg. Thank you for attention ! I am sorry to tell you that we have no plans to release this part of the experiment recently.But if it's convenient for you, you can send me an email to _longfei121@mail.dlut.edu.cn_, and I'd like to tell you how to reproduce our cross-domain experiments.
