### ISSUE TITLE
Could you provide a download link for the Stanford Cars dataset you used?

### ISSUE THREAD

**Issue by Hello-Vivian** [Fei-Long121/DeepBDC#23]

**Comment by JiamingLv** [comment]
For the Stanford Cars dataset we use the division of DN4. You can refer to this link for details: https://github.com/WenbinLee/DN4

**Comment by Hello-Vivian** [comment]
> For the Stanford Cars dataset we use the division of DN4. You can refer to this link for details: https://github.com/WenbinLee/DN4

I have seen this git warehouse, but the link to download the data set on the official website has been 404, so I want to ask if it is convenient for me to give me this data set?

**Comment by JiamingLv** [comment]
This is the BaiduCloud download link for Cars: https://pan.baidu.com/s/1TdEfsBS9q7LznZDlczaATg?pwd=2xup
