### ISSUE TITLE
关于protonet以及meta_deepbdc在miniimagenet上的结果

### ISSUE THREAD

**Issue by zyc0306** [Fei-Long121/DeepBDC#4]
您好！我对您的工作很感兴趣，但是复现protonet在miniimagenet上的结果时，用了预训练模型的情况下只有不到78的准确率，同样在使用您发布的meta_deepbdc模型在miniimagenet上测试时也只有77左右的准确率，请问这是参数没调好的原因吗？还是其他什么原因呢？

**Comment by Fei-Long121** [comment]
您好，感谢您的关注！我们自发布的代码以来，有多位同行进行了复现，所给模型应该是能在方差范围内复现我们的实验结果的。对于您所指出的这种情况，请检查您所用的数据集的划分是否与我们一致；此外，我们使用的miniImageNet是从ImageNet中抽取的原图(分辨率大小不一)而不是固定尺寸的图像。希望能对您有所帮助。

**Comment by zyc0306** [comment]
谢谢您的回复，确实是数据集问题，重新做了一下数据集就可以复现结果了

**Comment by Fei-Long121** [comment]
> 谢谢您的回复，确实是数据集问题，重新做了一下数据集就可以复现结果了

好的，多谢关注！

**Comment by RuizhiZhou** [comment]
您好，我在您提供的metadeepbdc的miniimagenet预训练模型上直接微调，为什么准确率到了89？而且我没有微调仅仅用您提供的预训练模型去测试准确率也有83点几，这是正常的吗
