### ISSUE TITLE
请问在bdc_module.py中 BDC函数的参数input_dim不是int类型的吗，为什么后面有input_dim[0],input_dim[1]，这些值代表的什么呢

### ISSUE THREAD

**Issue by zengmy969** [Fei-Long121/DeepBDC#6]
请问在bdc_module.py中 BDC函数的参数input_dim不是int类型的吗，为什么后面有input_dim[0],input_dim[1]，这些值代表的什么呢？

**Comment by JiamingLv** [comment]
@zengmy969 您好，首先感谢您对我们工作的关注。在BDC类的初始化函数里，参数input_dim表示为卷积神经网络输出的3位张量的维度，组成形式为[通道数，特征图的高，特征图的宽]；以ResNet12为例，由于我们的代码去掉了ResNet12最后一个Stage的降采样，因此input_dim为[640, 10, 10]。这个问题是我们代码书写的不够规范所导致，很抱歉对您造成了误解，之后我们会对此进行修改。

**Comment by zengmy969** [comment]
> @zengmy969 您好，首先感谢您对我们工作的关注。在BDC类的初始化函数里，参数input_dim表示为卷积神经网络输出的3位张量的维度，组成形式为[通道数，特征图的高，特征图的宽]；以ResNet12为例，由于我们的代码去掉了ResNet12最后一个Stage的降采样，因此input_dim为[640, 10, 10]。这个问题是我们代码书写的不够规范所导致，很抱歉对您造成了误解，之后我们会对此进行修改。
