### ISSUE TITLE
TieredImagenet蒸馏超参及蒸馏次数

### ISSUE THREAD

**Issue by xXuHaiyang** [Fei-Long121/DeepBDC#8]
您好！
请问STLDeepBDC在TieredImageNet上Distill的超参是和train的时候一致吗？
请问自蒸馏次数是多少？
谢谢！

**Comment by JiamingLv** [comment]
您好，感谢您关注我们的工作！STL DeepBDC在tieredImageNet上蒸馏和训练的超参是一致的，自蒸馏次数为1次。

**Comment by xXuHaiyang** [comment]
你好
mini-imagenet: https://www.zhihu.com/question/408666055 回答里可以找
tiered-imagenet: 我直接从imagenet中提取的，但是没有test数据集，因为imagenet的任务大家都是用train和val，和小样本任务的setting不太一样。因此也希望作者可以提供一下自己使用的tiered-imagenet的testset，谢谢！

**Comment by xue19890510** [comment]
@xXuHaiyang  你在tired-imagenet上复现了结果没有？
