### ISSUE TITLE
Could you please provide the link to download the datasets? thanks!

### ISSUE THREAD

**Issue by SethDeng** [Fei-Long121/DeepBDC#9]

**Comment by Fei-Long121** [comment]
Hi, thank you for your interests in our work.The spilts of the dataset has been clarified in the paper.For miniImageNet and tiered_ImageNet, we draw it from ImageNet 1K (ILSVRC2012).And the code links are as follows: miniImageNet:https://github.com/yaoyao-liu/mini-imagenet-tools  tiered_ImageNet:ttps://github.com/yaoyao-liu/tiered-imagenet-tools/tree/c297db8466bc0c43c0832baeee38b979868e3e64 And you need to note that like DeepEMD and FRN, etc., we save the original size of the image, not directly scaled to 84×84.Hope this information will help you!
